### ISSUE TITLE
Unpin Pillow

### ISSUE THREAD

**Issue by manthey** [imi-bigpicture/wsidicom#112]
Is there a reason Pillow is pinned to version 9.x?  Can it be unpinned to allow Pillow 10?  I think this is just changing https://github.com/imi-bigpicture/wsidicom/blob/main/pyproject.toml#L23

Thank you.

**Comment by erikogabrielsson** [comment]
Hi @manthey and thanks for posting this issue. I was not aware that Pillow 10 had been released. I have now changed the version dependency to include both Pillow 9 and 10.
