### ISSUE TITLE
Support combining multiple series for DICOMweb

### ISSUE THREAD

**Issue by psavery** [imi-bigpicture/wsidicom#118]
Similar to how the `WsiDicomFileSource` supports [being provided multiple files](https://github.com/imi-bigpicture/wsidicom/blob/774fe3ca00096e3fd2556fc956520dbfabc81311/wsidicom/file/wsidicom_file_source.py#L45), does it make sense to also allow multiple ~~study_uids/~~ series_uids [for the `WsiDicomWebSource`](https://github.com/imi-bigpicture/wsidicom/blob/774fe3ca00096e3fd2556fc956520dbfabc81311/wsidicom/web/wsidicom_web_source.py#L35-L36)?

For [this example](https://imagingdatacommons.github.io/slim/studies/1.3.6.1.4.1.5962.99.1.3456320082.756362073.1622659023442.3.0/series/1.3.6.1.4.1.5962.1.1.0.0.0.1595262375.18986.4?state=1.2.826.0.1.3680043.10.511.3.27858314868153043883718705496433854), for instance, there are many optical paths, and most of the optical paths are located in separate series. It would be nice if we could instantiate a `WsiDicomWebSource` that contains all of these optical paths.

I would be happy to put up a PR for this if you think it sounds like a good idea.

**Comment by erikogabrielsson** [comment]
Allowing loading multiple series sounds good. Im not so sure about multiple studies. Is there a use-case for that? It will make patient and study level metadata for the wsi much more complicated. 

Note that `WsiDicomFileSource` considers instances to be part of the pyramid if they have same study, series, and frame of reference uid. This is to strict, it should be enough that the frame of reference matches*.  So if you implement this, please add a check that the obtained instances have the same frame of reference. 

* Ideally we should also check that the `TotalPixelMatrixOriginSequence` is the same, as there might be multiple pyramids on the same slide (i.e. frame of reference). It might also be worth implementing support for multiple pyramids.

**Comment by psavery** [comment]
> Allowing loading multiple series sounds good. Im not so sure about multiple studies. Is there a use-case for that? It will make patient and study level metadata for the wsi much more complicated.

No, I don't actually have an example that requires multiple studies, just multiple series, so we can go with that!

> Note that `WsiDicomFileSource` considers instances to be part of the pyramid if they have same study, series, and frame of reference uid. This is to strict, it should be enough that the frame of reference matches*. So if you implement this, please add a check that the obtained instances have the same frame of reference.

Sounds good.

> * Ideally we should also check that the `TotalPixelMatrixOriginSequence` is the same, as there might be multiple pyramids on the same slide (i.e. frame of reference). It might also be worth implementing support for multiple pyramids.

Sounds good also!
