### ISSUE TITLE
Failed to parse LUT

### ISSUE THREAD

**Issue by psavery** [imi-bigpicture/wsidicom#129]
If I run the following example:

```python
from wsidicom import WsiDicom, WsiDicomWebClient

url = 'https://idc-external-006.uc.r.appspot.com/dcm4chee-arc/aets/DCM4CHEE/rs'
study_uid = '2.16.756.5.41.446.20190905094928'
series_uid = '2.16.756.5.41.446.20190905094928.20190905102252'

client = WsiDicomWebClient.create_client(url)

slide = WsiDicom.open_web(client, study_uid, series_uid)
```

I get this error:
```python
ERROR:root:Failed to parse LUT
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/histomics/src/wsidicom/wsidicom/optical.py", line 106, in from_ds
    return cls(ds.PaletteColorLookupTableSequence)
  File "/home/patrick/virtualenvs/histomics/src/wsidicom/wsidicom/optical.py", line 62, in __init__
    self.table = self._parse_lut(self._lut_item)
  File "/home/patrick/virtualenvs/histomics/src/wsidicom/wsidicom/optical.py", line 156, in _parse_lut
    parsed_tables[color] = self._parse_color(table)
ValueError: could not broadcast input array from shape (65536,) into shape (0,)
```

That example is located [here](https://imagingdatacommons.github.io/slim/studies/2.16.756.5.41.446.20190905094928/series/2.16.756.5.41.446.20190905094928.20190905102252).

**Comment by erikogabrielsson** [comment]
Thanks, I have also noticed that the LUT parsing fails on this example. I did wrap the parsing in a try-except block, setting the LUT to None if it failed to parsed. I have not yet had time to check if it is the LUT parser that is wrong (likely) or the LUT in the dataset. 

I know that the LUT parser in the current release does not cover the standard properly. It will be replaced once I merge [this branch](https://github.com/sectra-medical/wsidicom/blob/metadata/wsidicom/metadata/dicom_schema/optical_path.py#L72).

**Comment by erikogabrielsson** [comment]
I can no longer access the slim example. Do you have the lut sequences so that I can test them?

**Comment by psavery** [comment]
Unfortunately, I do not have them :slightly_frowning_face:. They are fixing the slim example, hopefully we'll be able to access it again soon.

**Comment by erikogabrielsson** [comment]
Closing this for now. I think the LUT would have been parsed OK with the new parser, but I cant find the slide on IDC.
