### ISSUE TITLE
Not working with pydicom 3.0

### ISSUE THREAD

**Issue by erikogabrielsson** [imi-bigpicture/wsidicom#165]
There are a lot of changes in pydicom 3.0 that breaks the current version of wsidicom.

**Comment by DanielaSchacherer** [comment]
Probably related: when I try to import WsiDicom from wsidicom, I receive the following error. 

![image](https://github.com/user-attachments/assets/9d138f1f-9a4d-4d21-931d-fd5facdfe246)

**Comment by fedorov** [comment]
@erikogabrielsson would it make sense to freeze pydicom version to a latest pre-3.0 version that is known to work until this issue is resolved?

**Comment by erikogabrielsson** [comment]
@DanielaSchacherer yes, it is the same problem. See [this branch](https://github.com/imi-bigpicture/wsidicom/tree/pydicom-3.0) for a fix.

**Comment by erikogabrielsson** [comment]
Release [0.20.6](https://github.com/imi-bigpicture/wsidicom/releases/tag/v0.20.6) works on pydicom 2.
Release [0.21.0](https://github.com/imi-bigpicture/wsidicom/releases/tag/v0.21.0) works on pydicom 3.
