### ISSUE TITLE
numpy 2.0

### ISSUE THREAD

**Issue by manthey** [imi-bigpicture/wsidicom#168]
The most recently published version (0.9.0) requires numpy < 2.0.  Can this be unpinned?  This is done via poetry in the pyproject.toml file.

**Comment by erikogabrielsson** [comment]
Unpinned in [This branch](https://github.com/imi-bigpicture/wsidicom/tree/Numpy-2). Waiting for new release of dicomweb-client before releasing.

**Comment by manthey** [comment]
Thank you.
