### ISSUE TITLE
DICOM Metadata needed accoding to MSMdad

### ISSUE THREAD

**Issue by 11777840** [imi-bigpicture/wsidicom#172]
Hi Erik,

when using one of these calls, the extracted metadata do not include image_size or base_layer_tile_size. Is there a possibilty to extract these values with wsidicom?

with WsiDicom.open(folder_path) as wsi:
         metadata = wsi.levels.base_level.datasets[0]
         #metadata = wsi.metadata

If not it would be to great to include the function for all values mandatory in MSMdad needed from the converted DICOM.

Thanks!

**Comment by erikogabrielsson** [comment]
@11777840 Here is an example from bigpicture-slidetap on how to use the dataset and metadata to create bigpicture image metadata. Let me know if you dont have access to the repo:
https://github.com/imi-bigpicture/bigpicture-slidetap/blob/main/bigpicture_slidetap/processors/image_pre_processor.py#L71

**Comment by 11777840** [comment]
Thanks, worked out fine!

**Comment by erikogabrielsson** [comment]
Perfect!
