### ISSUE TITLE
read_region() : blank spaces not blank as zoom level increases

### ISSUE THREAD

**Issue by chlmarchal** [imi-bigpicture/wsidicom#47]
Hello! 

I wanted to use your library to read some WSI Dicom files. In this case, I took the image "melanoma_pilot_003" that can be seen in file "region_wsidicom_level7". 

I wanted to use the `read_window` function to extract a particular window from the image:
```
from wsidicom import WsiDicom

slide = WsiDicom.open("./melanoma_pilot_003")
region = slide.read_region((0, 0),4, (3968, 4672))
region.save("./region_wsidicom_level4.png", format="png")
```
When I increase the zoom level the image area that is supposed to be blank is not. As I increase the zoom level, the image is repeated more and more. This can be seen in images "region_wsidicom_level5" and "region_wsidicom_level4", where the bottom of the images that is suppose to be blank isn't. This can be compared with the image obtained at zoom level 7 where there is nothing in the blank areas. 

Have you already observed this phenomenon? 

Have a nice day!

![region_wsidicom_level4](https://user-images.githubusercontent.com/91737269/154229025-686a4454-f9e9-4fd3-bb6d-b3a0d56849ae.png)
![region_wsidicom_level5](https://user-images.githubusercontent.com/91737269/154229029-9a4eda19-e996-4ab1-8e41-429211e66b65.png)
![region_wsidicom_level7](https://user-images.githubusercontent.com/91737269/154229030-e79abc61-6339-45cb-ab1e-6394036e451f.png)

**Comment by erikogabrielsson** [comment]
Thanks for reporting this @chlmarchal. This is actually a bug in opentile, which was used to dicomize the tiff-files. The function for generating blank tiles to fill in the sparse tiles in the tiff file takes the first valid tile in the pyramid level (e.g. the top left corner) and fills it with the background color. The left the ac components unchanged, and those thus appeared in the blank tiles.

**Comment by chlmarchal** [comment]
Thanks for the information and your pull request.
