### ISSUE TITLE
Overflow error when opening DICOM-TIFF image with wsidicom

### ISSUE THREAD

**Issue by DanielaSchacherer** [imi-bigpicture/wsidicom#49]
While trying to open a DICOM-TIFF object with wsidicom, I encoutered the following error. Can anyone give me some advice on that?
![Image Pasted at 2022-3-16 17-40](https://user-images.githubusercontent.com/11156673/159732576-2d48c613-827a-4a0b-913d-05a12f00f6da.jpg)

**Comment by erikogabrielsson** [comment]
Hi Daniela,
Could you provide the whole stack trace for the error? I looks like miss-formatted value, and a possible workaround could be to relax the pydicom parsing. You could try (after importing wsidicom):
````python
from pydicom import config
config.enforce_valid_values = False
````

**Comment by DanielaSchacherer** [comment]
Hi @erikogabrielsson, 
thanks a lot for your fast answer. Me and also colleagues from mine checked the respective DICOM file and everything seemed well-formatted. However, your suggestion fixed the error. :) 

For completion here is the whole stack trace for the error: 
![Bildschirmfoto vom 2022-03-24 15-39-26](https://user-images.githubusercontent.com/11156673/159941648-61796029-bec3-4332-9317-6b3a31c5c1c3.png)

![Bildschirmfoto vom 2022-03-24 15-40-04](https://user-images.githubusercontent.com/11156673/159941689-eb38a497-d48e-4845-9feb-122fdf44f65a.png)

Thanks again!

**Comment by dclunie** [comment]
Why is the pydicom code failing when the check is performed when the value is valid?

Shouldn't pydicom be fixed rather than worked around by deactivating the check, which might be valuable under other circumstances?

**Comment by DanielaSchacherer** [comment]
No problem - thanks for helping out so fast. But I agree with David Clunie, this is probably an issue that should be reported to pydicom. I can do that and link this issue, if everyone here agrees :)

**Comment by erikogabrielsson** [comment]
Was this issue raised in the pydicom repo?
