### ISSUE TITLE
Add recipie for conda

### ISSUE THREAD

**Issue by shaneahmed** [imi-bigpicture/wsidicom#57]
- It would be great if this was available on conda in addition to pip for the wider community.

**Comment by shaneahmed** [comment]
conda-forge package PR at 
https://github.com/conda-forge/staged-recipes/pull/18878

**Comment by jesper-molin** [comment]
@sarthakpati Very nice work, I have verified that this works in a conda environment on my computer as well and I agree that it is good idea to to add it to the readme.
It looks like the conda recipe is locked to version 0.3.1, what is a good routine to make sure that the conda version is up to date when we release new versions of the pip package?

**Comment by sarthakpati** [comment]
As long as it is updated on pip, conda bots will pick it up and auto-merge (as long as all CI builds pass). Happy to provide more details if you need. 😄

**Comment by shaneahmed** [comment]
Thanks @sarthakpati

**Comment by sarthakpati** [comment]
> As long as it is updated on pip, conda bots will pick it up and auto-merge (as long as all CI builds pass). Happy to provide more details if you need. 😄

FYI, live example right here with the 0.3.2 release: https://github.com/conda-forge/wsidicom-feedstock/pull/3
