### ISSUE TITLE
add_missing_levels does not recreate missing levels

### ISSUE THREAD

**Issue by nstatho** [imi-bigpicture/wsidicom#97]
I used the add_missing_levels option to recreate the pyramid structure of DICOM file but it did not recreate the pyramid structure.

If I look into the code, in this line:
https://github.com/imi-bigpicture/wsidicom/blob/90671211ddb87096d19952d5e80a7199dda51b67/wsidicom
/file/wsidicom_file_target.py#LL79C1-L79C44

it seems that new_levels is set to "None" and then it never enters the "if" check later on.

**Comment by erikogabrielsson** [comment]
Hi @nstatho,
Your observation is correct. Additionally the target-object is not used as a context in the WsiDicom.save() method so any new pyramid levels would be left open.

I have a draft for a fix here #100, but would like to test it more before merging.

**Comment by erikogabrielsson** [comment]
@nstatho Can you try the fix in the PR #100?

**Comment by nstatho** [comment]
I tried it and it seems to work. I tested it on several DICOMs and all except one gave an error. The error I got from that one DICOM seems to be related to that one specific file. 

This is the error:
`Frame count 2040 != Fragments 2023. Fragmented frames are not supported`

**Comment by nstatho** [comment]
Yes it worked with all except one indeed. I'll send you the file on a separate email to take a look. 
If I view the file in PACS, you see black and white squares on certain magnifications so I think the file itself has an issue.

**Comment by nstatho** [comment]
Yes it worked with all except one indeed. I'll send you the file on a separate email to take a look. 
If I view the file in PACS, you see black and white squares on certain magnifications so I think the file itself has an issue.

**Comment by erikogabrielsson** [comment]
The second and third layer seems to be missing tiles on the bottom row. For example, `dataset.NumberOfFrames` returns 2040 but `len(dataset.PerFrameFunctionalGroupsSequence)`  returns 2023.
