### ISSUE TITLE
need to read from google cloud bucket

### ISSUE THREAD

**Issue by zergxyz** [imi-bigpicture/wsidicom#99]
Hello. I need to read those dicom files from the gcp cloud storage bucket. Is there any way I can pass the gs link to the WsiDicom.open() method?

**Comment by erikogabrielsson** [comment]
Hi @zergxyz 
What API can be used to access your files in the storage bucket?

**Comment by zergxyz** [comment]
Hello Erik @erikogabrielsson 
I am using Apache Beam (Cloud Dataflow) to read DICOM files from the cloud storage buckets. Each file will be read as the binary data and I can also convert them as bytes through DicomBytesIO(dicom_bn) in pydicom. I wish in our wsidicom lib we can implemente something similar to pydicom.dcmread() to accept not only string but also bytes and binaryIO. Or maybe there are some other smater ways to achieve this as well. Thanks

**Comment by erikogabrielsson** [comment]
There is work in progress to enable reading from streams. The motive has been to enable direct read of encrypted (with [crypt4gh](https://www.ga4gh.org/news/crypt4gh-a-secure-method-for-sharing-human-genetic-data/)) slides stored in S3 buckets, but the same solution should likely also be useful for your use case.

I will clean up the code and make a branch.

**Comment by erikogabrielsson** [comment]
There is a draft for extending WsiDicom.open() to handle streams here #101

**Comment by erikogabrielsson** [comment]
Support for handling opened streams is included in #106 .
